version: '2'
services:
  flyway:
    image: flyway/flyway
    container_name: migrations
    command: -url=jdbc:mysql://mydb:3306/mysql -schemas=app -user=root -password=1234 -connectRetries=60 migrate
    volumes:
      - /src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    container_name: mydb
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  app:
    build: .
    container_name: telegram-app
    ports:
      - "8080:8080"
    depends_on:
      - flyway